resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/1fc576f290d24738fa70d90027e6774e3ae88c99/snapshot.yaml

packages:
  - binary
  - binary/test
  - cardano-crypto-class

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 12ab51e27539c9cce042ded0c89efc0ccae6137a
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
