resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/2256fd727c5f92e6218afdcf8cddf6e01c4a9dcd/snapshot.yaml

packages:
  - binary
  - binary/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 2256fd727c5f92e6218afdcf8cddf6e01c4a9dcd
    subdirs:
      - .
      - test

nix:
  shell-file: ./scripts/nix/stack-shell.nix
