resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/b83730dccab14111d62144b048084eec7900d091/snapshot.yaml

packages:
  - binary
  - binary/test
  - cardano-crypto-class

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: b83730dccab14111d62144b048084eec7900d091
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
