resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/d8091767addc1a51e11cb2f04392e4eb40e39b18/snapshot.yaml

packages:
  - binary
  - binary/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: d8091767addc1a51e11cb2f04392e4eb40e39b17
    subdirs:
      - .
      - test

nix:
  shell-file: ./scripts/nix/stack-shell.nix
