resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/fda38e60007a019c0c8569e8a0fc08f2102c92cc/snapshot.yaml

packages:
  - binary
  - binary/test
  - cardano-crypto-class

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: fda38e60007a019c0c8569e8a0fc08f2102c92cc
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
