resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/cb4c0673b1d7220e3f18b808ff959e0060e61988/snapshot.yaml
compiler: ghc-8.6.5

packages:
  - binary
  - binary/test
  - cardano-crypto-class
  - slotting

ghc-options:
  binary:                 -Wall
  binary-test:            -Wall
  cardano-crypto-class:   -Wall
  slotting:               -Wall

allow-newer: true

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: cb4c0673b1d7220e3f18b808ff959e0060e61988
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
