resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/a136c4242b9c9f6124b811329bc8ccdfd86c514e/snapshot.yaml

packages:
  - binary
  - binary/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: a136c4242b9c9f6124b811329bc8ccdfd86c514e
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
