resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/fa7a16291d3e93b068d9b13620fc81c88b5600f0/snapshot.yaml
compiler: ghc-8.6.5

packages:
  - binary
  - binary/test
  - cardano-crypto-class
  - slotting

ghc-options:
  binary:                 -Wall
  binary-test:            -Wall
  cardano-crypto-class:   -Wall
  slotting:               -Wall

allow-newer: true

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: fa7a16291d3e93b068d9b13620fc81c88b5600f0
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
