resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/56fadcea03417771f4b3666fd1dfc9bad8df1484/snapshot.yaml

packages:
  - binary
  - binary/test
  - cardano-crypto-class

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 56fadcea03417771f4b3666fd1dfc9bad8df1484
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
