resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/71c0b1340e0b47d6f463c005406468b49d603dc6/snapshot.yaml

packages:
  - binary
  - binary/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 71c0b1340e0b47d6f463c005406468b49d603dc6
    subdirs:
      - .
      - test

nix:
  shell-file: ./scripts/nix/stack-shell.nix
