resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/ab1c4a09d6b0c8b44a4e2382ea68ddc67bc3c274/snapshot.yaml

packages:
  - binary
  - binary/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: ab1c4a09d6b0c8b44a4e2382ea68ddc67bc3c274
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
