resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/57fcc83702b91e0a7aecdb32c99ab1d8c1c444d0/snapshot.yaml
compiler: ghc-8.6.5

packages:
  - binary
  - binary/test
  - cardano-crypto-class
  - slotting

ghc-options:
  binary:                 -Wall
  binary-test:            -Wall
  cardano-crypto-class:   -Wall
  slotting:               -Wall

allow-newer: true

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 57fcc83702b91e0a7aecdb32c99ab1d8c1c444d0
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
