resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/316c854d1d3089f480708ad5cd5ecf8a74423ddd/snapshot.yaml
compiler: ghc-8.6.5

packages:
  - binary
  - binary/test
  - cardano-crypto-class
  - slotting

ghc-options:
  binary:                 -Wall
  binary-test:            -Wall
  cardano-crypto-class:   -Wall
  slotting:               -Wall

allow-newer: true

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 316c854d1d3089f480708ad5cd5ecf8a74423ddd
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
