resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/001ec3576ef3bda04cf5bcccdd9a00991835d1a7/snapshot.yaml

packages:
  - binary
  - binary/test
  - cardano-crypto-class

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 001ec3576ef3bda04cf5bcccdd9a00991835d1a7
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
