resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/dc40b2e60cee4e808ffaa275926ade74a6c987d1/snapshot.yaml

packages:
  - binary
  - binary/test
  - cardano-crypto-class

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: dc40b2e60cee4e808ffaa275926ade74a6c987d1
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
