resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/2a101186441ee0e60d4fcc4abd94c1a4a5cc4e9e/snapshot.yaml
compiler: ghc-8.6.5

packages:
  - binary
  - binary/test
  - cardano-crypto-class
  - slotting

ghc-options:
  binary:                 -Wall
  binary-test:            -Wall
  cardano-crypto-class:   -Wall
  slotting:               -Wall

allow-newer: true

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 2a101186441ee0e60d4fcc4abd94c1a4a5cc4e9e
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
