resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/f12a60595dbc2436d99a198b717bf26a683b5eec/snapshot.yaml

packages:
  - binary
  - binary/test
  - cardano-crypto-class

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: f12a60595dbc2436d99a198b717bf26a683b5eec
    subdirs:
      - .
      - test

nix:
  shell-file: ./nix/stack-shell.nix
